version: "3.9"
services:
  microman:
    build:
      context: ../
      dockerfile: ../Dockerfile
      target: dev
    container_name: ${SERVICE_NAME}
    ports:
      - ${EXPORTED_APP_PORT}:${APP_PORT}

